version: '3'

name: snipeit

services:
  php.service:
    container_name: snipeit_php
    build: ./docker
    volumes:
      - .:/var/www/html
    env_file:
      - .env.docker
    depends_on:
      - mariadb
      - redis

  nginx.service:
    container_name: snipeit_nginx
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php.service

  mariadb:
    container_name: snipeit_db
    image: mariadb:10.6.4-focal
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env.docker
    ports:
      - "33060:3306"

  redis:
    container_name: snipeit_redis
    image: redis:6.2.5-buster

  mailhog:
    container_name: snipeit_mailhog
    image: mailhog/mailhog:v1.0.1
    ports:
      # - 1025:1025
      - "8025:8025"

volumes:
  db: {}
